"why only got small part of null point exception stack i got nullpointexception from below place...at blank.util.concurrent.futuretask$sync.innerget(futuretask.blank:222).at blank.util.concurrent.futuretask.get(futuretask.blank:83)...because i user threadpoolexecutor, and get exception in this thread method. and then i have other method which override afterexecute:..   @override.protected void afterexecute(runnable r, throwable t) {...and i call other method in afterexecute:..    t result = future.get();...this method will cause null point exception:..my question is that..when first several times, i get exception. i can see the exception's fully log..but after that, i only can see small part of this exception:..1st several times: ..blank.lang.nullpointerexception.    at blank.util.concurrent.futuretask$sync.innerget(futuretask.blank:222).    at blank.util.concurrent.futuretask.get(futuretask.blank:83).    at com.xxxxx.xxxxx.execution.abstractexecutionunit.getresult(abstractexecutionunit.blank:93).    at com.xxxxx.xxxxx.execution.abstractexecutionunit.afterexecute(abstractexecutionunit.blank:153).    at blank.util.concurrent.threadpoolexecutor$worker.runtask(threadpoolexecutor.blank:888).    at blank.util.concurrent.threadpoolexecutor$worker.run(threadpoolexecutor.blank:908).    at blank.lang.thread.run(thread.blank:619).caused by: blank.lang.nullpointerexception.    at com.xxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx(betradarcache.blank:134).    at com.xxxxx.xxxxx.execution.omdatamodelserviceimpl$10.call(omdatamodelserviceimpl.blank:1010).    at com.xxxxx.xxxxx.execution.omdatamodelserviceimpl$10.call(omdatamodelserviceimpl.blank:999).    at blank.util.concurrent.futuretask$sync.innerrun(futuretask.blank:303).    at blank.util.concurrent.futuretask.run(futuretask.blank:138).    at blank.util.concurrent.threadpoolexecutor$worker.runtask(threadpoolexecutor.blank:886).    ... 2 more...after that:..blank.lang.nullpointerexception.at blank.util.concurrent.futuretask$sync.innerget(futuretask.blank:222).at blank.util.concurrent.futuretask.get(futuretask.blank:83).at com.xxxxx.xxxxx.execution.abstractexecutionunit.getresult(abstractexecutionunit.blank:93).at com.xxxxx.xxxxx.execution.abstractexecutionunit.afterexecute(abstractexecutionunit.blank:153).at blank.util.concurrent.threadpoolexecutor$worker.runtask(threadpoolexecutor.blank:888).at blank.util.concurrent.threadpoolexecutor$worker.run(threadpoolexecutor.blank:908).at blank.lang.thread.run(thread.blank:619)...why the log is different? i really appreciate if someone can explain the reason."
