"poolofflineexception: [host=host [hostname=unknown, ipaddress=unknown, port=0, rack: getting pool offline exception when i try connect to dynomite cluster using dyno client..have tried to increase the max connections per host and not much luck. i am running with 6 node cluster with 3 racks. and i a requirement to support 35k ops/sec. its working fine initially when i keep on increasing the load it throwing pooloffline exceptions..    dynoclusterclient   = new dynojedisclient.builder().                    .withapplicationname(clientmetrics).                    .withdynomiteclustername(clustermetrics).                    .withcpconfig(new archaiusconnectionpoolconfiguration(clientmetrics).                            .withtokensupplier(tokenmapsupplierhelper.totokenmapsupplier(nodes)).                            .setmaxconnsperhost(maxconnectionsmetrics).                            .setconnecttimeout(maxtimeoutmetrics).                            .setretrypolicyfactory(new retryntimes.retryfactory(retrycountmetrics,true)).                            .setmaxtimeoutwhenexhausted(maxtimeoutexhaustedmetrics).                            ).                    .withhostsupplier(tokenmapsupplierhelper.tohostsupplier(nodes)).                    .build();"
