"unittest.main() not working within main() i am learning unittest on class and encounter a problem that unittest.main() can not run within main function:..here is the class anonymoussurvey which collects anonymous answers to a survey question...import unittest..class anonymoussurvey:.    """"""collect anonymous answers to a survey question.""""""..    def __init__(self, question):.        self.question = question.        self.responses = []..    def show_question(self):.        print(question)..    def store_response(self, new_response):.        self.responses.append(new_response) ..    def show_results(self):.        print(""survey results:"").        for response in self.responses: .            print(""- "" + response)...the unittest is encapsulated in a main() function...def main():..    class testanonymoussurvey(unittest.testcase):.        """"""test that a single response is stored properly""""""..        def test_store_single_response(self):.            question = ""what language did you first learn to speak?"".            my_survey = anonymoussurvey(question).            my_survey.store_response(""english"")..            self.assertin(""english"", my_survey.responses)..    unittest.main()....if __name__ == ""__main__"":.    main()...it report ran0 tests..in [64]: !blank survey.py                                                                                        ..----------------------------------------------------------------------.ran 0 tests in 0.000s..ok...how could i get it working within a main() area?"
