"indexerror: index 11 is out of bounds for axis 1 with size 11 please can one advise why i am getting this error message please:..indexerror                                traceback (most recent call last). in .      1 # import some data to play with.      2 nd = train_x_all.values.----> 3 x = nd[:,[11,5]]  # we only take the first two features..      4 y = train_y_all.values.      5 ..indexerror: index 11 is out of bounds for axis 1 with size 11..# import some data to play with.nd = train_x_all.values.x = nd[:,[11,5]]  # we only take the first two features..y = train_y_all.values..logreg = logisticregressioncv(cv=10)..# create an instance of logistic regression classifier and fit the data..logreg.fit(x, y).x_min, x_max = x[:,0].min() - 1, x[:,0].max() + 1.y_min, y_max = x[:,1].min() - 1, x[:,1].max() + 1.xx, yy = np.meshgrid(np.arange(x_min, x_max,0.1),.                     np.arange(y_min,y_max, 0.1)).z = logreg.predict(np.c_[xx.ravel(), yy.ravel()]).z = z.reshape(xx.shape).plt.plot().plt.contourf(xx, yy, z, alpha=0.4, cmap = plt.cm.rdylbu).plt.scatter(x[:, 0], x[:, 1], c=y,  cmap = plt.cm.brg).plt.title(""logistic regression"").plt.xlabel(""familyn"").plt.ylabel(""fare"").plt.legend(y).plt.show()"
