"system-error after some specific input in input() function. (in bash shell) systemerror after entering some string then pressing ctrl+d twice or more or some characters then ctrl+c...i know that pressing ctrl+d raises an eoferror if pressed first...systemerror can be handeled but why does it throw a systemerror after doing the above?..pressing(after entering some text) ctrl+d just once and then ctrl+c raises a keyboardinterrupt error and that is handeled...code:..tmp = none..try:.    tmp = input().except keyboardinterrupt:.    print(""exit"").    exit(130)...input: teststring^d^d^c..traceback:..$ blank test.py.teststring^ckeyboardinterrupt # input 'teststring^d^d^c'..the above exception was the direct cause of the following exception:..traceback (most recent call last):.  file ""test.py"", line 4, in &lt;module&gt;.    tmp = input().systemerror: &lt;built-in function input&gt; returned a result with an error set...shell: bash 5.0.7.blank: blank 3.7.4"
