"blank pydf throwing exception 'module' object has no attribute 'poll' i've been struggling with this exception for a while. .simply i'm trying to save a string into a pdf using pydf library. this is quite straight forward as in here. if i run the below script in a standalone blank script it works perfectly fine..import pydf.alarm_report = ""test"".file_name = ""test.pdf"".pdf = pydf.generate_pdf(alarm_report).   with open(str(file_name), 'w') as f:.   f.write(pdf)...however, when i try to integrate it into the software i'm developing i get the following exception:..file ""/home/cayman/multiviewer/src/alarm_log/alarm_db_utils.py"", line 116, in db_export_to_pdf.    pdf = pydf.generate_pdf(str(alarm_report))   file ""/usr/local/lib/blank2.7/dist-packages/pydf/wkhtmltopdf.py"", line 121, in generate_pdf.    return gen_pdf(html_file.name, cmd_args)   file ""/usr/local/lib/blank2.7/dist-packages/pydf/wkhtmltopdf.py"", line 105, in gen_pdf.    _, stderr, returncode = execute_wk(*cmd_args)   file ""/usr/local/lib/blank2.7/dist-packages/pydf/wkhtmltopdf.py"", line 23, in execute_wk.    stdout, stderr = p.communicate()   file ""/usr/lib/blank2.7/subprocess.py"", line 799, in communicate.    return self._communicate(input)   file ""/usr/lib/blank2.7/subprocess.py"", line 1409, in _communicate.    stdout, stderr = self._communicate_with_poll(input)   file ""/usr/lib/blank2.7/subprocess.py"", line 1439, in._communicate_with_poll.    poller = select.poll()...any idea what's causing this problem ?"
