"blank name error in dict comprehension when called inside a function i have the following blank2 code which gives a nameerror:..def myfunc():...   myvar=50.    print myvar.    print eval('myvar').    a = 'myvar'.    print { a:eval(a) }.    print { a:a for a in ['myvar'] }.    print { a:eval(a) for a in ['myvar'] }..myfunc()...and when i now execute this blank code with blank2, i get the following output:..50.50.{'myvar': 50}.{'myvar': 'myvar'}.traceback (most recent call last):.  file ""tester.py"", line 13, in &lt;module&gt;.    myfunc().  file ""tester.py"", line 11, in myfunc.    print { a:eval(a) for a in ['myvar'] }.  file ""tester.py"", line 11, in &lt;dictcomp&gt;.    print { a:eval(a) for a in ['myvar'] }.  file ""&lt;string&gt;"", line 1, in &lt;module&gt;.nameerror: name 'myvar' is not defined...remark: this is running on a mac....when i run the code snippet outside of a function it works as expected..."
