"why is the post increment operation executed if the line throws an exception? i came across a language behavior today that i wasn't expecting. now i'm eager to learn why. consider the following example:..try.{.    worksheet.addcell(row, cell++, image.displaycaption());.}.catch (nullreferenceexception).{.    cell++;.    throw;.}...in my example, image was null causing this line to throw a nullreferenceexception; however, cell was still incremented and, of course, it was incremented again in the catch block. why was the first post increment operation executed? in addition, would it have been executed if worksheet was null?..thanks, pete"
