"is empty tuple(takewhile()) advancing my iterator in blank? blank 3.5.4..if i pass a list_iterator to takewhile, then iterate over the takewhile object, the list_iterator is advanced, even when the takewhile object takes nothing. this does not happen when i pass a range object to takewhile. if this is expected behavior, then i've got something to learn...def range_vs_iter():..    # expected works as expected. surprise does not..    expected = range(5).    surprise = iter([0, 1, 2, 3, 4])..    # both of these produce an empty tuple.    print(tuple(takewhile(lambda x: false, expected))).    print(tuple(takewhile(lambda x: false, surprise)))..    # the first element in surprise has disappeared.    print(tuple(expected)) # (0, 1, 2, 3, 4).    print(tuple(surprise)) #    (1, 2, 3, 4)..    # if i don't iterate over takewhile object, everything is fine.    my_iter = iter([0, 1, 2, 3, 4]).    takewhile(lambda x: false, my_iter).    print(tuple(my_iter)) # (0, 1, 2, 3, 4)"
